name: C++ CI Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install g++

    - name: Build the code
      run: g++ -o main main.cpp hello.cpp

    - name: Run the executable
      run: ./main
